[graph]
all-features = true
no-default-features = false

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "ISC",
]
# The confidence threshold for detecting a license from license text.
# The higher the value, the more closely the license text must be to the
# canonical license text of a valid SPDX license file.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 0.9

exceptions = [
    { allow = ["Zlib"], crate = "foldhash" },
    { allow = ["OpenSSL"], crate = "aws-lc-sys" },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
skip-tree = [
    { crate = "windows-sys", depth = 3 },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
