//! Backend-neutral description of a proxy-generated response head.
//!
//! Every response the proxy *originates* (cache hit, conditional 304/416,
//! rejection or error page, upstream-relay failure, throttle 503, CONNECT
//! tunnel establishment) is described by a [`ResponseHead`] and rendered by
//! exactly one of two functions: `ResponseHead::into_hyper` for the hyper
//! backend and `ResponseHead::write_to` for the raw-socket sendfile/splice
//! backends.  Responses *relayed* from upstream (passthrough, streamed
//! downloads carrying the origin's headers) are not built here; those paths
//! only append `Via:` to the origin's header set.
//!
//! # Contract
//!
//! The renderers, not the call sites, own the headers that RFC 9110 and the
//! project policy require on every proxy-generated response:
//!
//! - `Via:` ([RFC 9110 §7.6.3]) and `Date:` are emitted unconditionally.
//! - `Connection:` is emitted on every response except the CONNECT `200`
//!   ([`ResponseKind::TunnelEstablished`]): that response precedes a
//!   protocol switch and hyper manages the upgrade itself.
//! - `Server:` is emitted only for [`ResponseKind::Error`] and the CONNECT
//!   `200`.  Success responses (cache hits, 304s, the parallel-download
//!   hack) never advertise it — keep that asymmetry.
//! - `Allow: GET` is emitted on every `405` ([RFC 9110 §15.5.6] makes it
//!   mandatory).
//!
//! Everything else (`Content-Type`, `Content-Length`, `Content-Range`,
//! `Last-Modified`, `ETag`, `Age`, `Accept-Ranges`, `Retry-After`) is an
//! explicit field a call site fills in.  A field is emitted iff it is set;
//! the renderers add no defaults of their own beyond the contract above.
//! The hyper renderer leaves an unset `Content-Length` to hyper, which
//! derives it from the body's size hint.
//!
//! A new proxy-generated response must be built from a [`ResponseHead`] —
//! not from a hand-written `Response::builder()` chain or `format!`
//! template — so the `Via`/`Server` invariant stays enforced by these two
//! renderers rather than by grep.
//!
//! [RFC 9110 §7.6.3]: https://www.rfc-editor.org/rfc/rfc9110#section-7.6.3
//! [RFC 9110 §15.5.6]: https://www.rfc-editor.org/rfc/rfc9110#section-15.5.6

use std::borrow::Cow;

use http::StatusCode;

#[cfg(feature = "sendfile")]
use crate::http_helpers::{ConnectionAction, ConnectionVersion};

/// Whether a response advertises the proxy as its origin.
///
/// Selects the `Server:` and `Connection:` policy in the renderers; see the
/// module documentation for the contract.
#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub(crate) enum ResponseKind {
    /// Cache hit, conditional `304`, or another response that answers the
    /// request on the origin's behalf: no `Server:`.
    Success,
    /// Rejection, error page, or upstream-relay failure generated by the
    /// proxy itself: carries `Server:`.
    Error,
    /// The `200 Connection Established` answer to a `CONNECT` request:
    /// carries `Server:`, omits `Connection:`, and renders the
    /// `Connection Established` reason phrase on the raw-socket path.
    TunnelEstablished,
}

/// Content type of every proxy-generated error body.
const TEXT_PLAIN_UTF8: &str = "text/plain; charset=utf-8";

/// A proxy-generated response head, independent of the serving backend.
///
/// Construct via the `ResponseHead::*` constructors and fill the remaining
/// fields with struct-update syntax; every field is `pub(crate)` so a call
/// site states exactly which optional headers it emits.
#[derive(Clone, Debug)]
pub(crate) struct ResponseHead<'a> {
    pub(crate) status: StatusCode,
    pub(crate) kind: ResponseKind,
    /// `Content-Length`.  The hyper renderer emits it only when set (hyper
    /// derives it from the body otherwise); the raw-socket renderer emits
    /// it only when set, so bodiless heads must set `Some(0)` explicitly.
    pub(crate) content_length: Option<u64>,
    pub(crate) content_type: Option<&'static str>,
    /// Emit `Accept-Ranges: bytes`.
    pub(crate) accept_ranges: bool,
    pub(crate) last_modified: Option<&'a str>,
    pub(crate) etag: Option<&'a str>,
    pub(crate) age: Option<u32>,
    pub(crate) content_range: Option<Cow<'a, str>>,
    /// `Retry-After`, in seconds.
    pub(crate) retry_after: Option<u32>,
}

impl<'a> ResponseHead<'a> {
    /// A head with only the status and kind set; every optional header off.
    #[must_use]
    pub(crate) const fn bare(status: StatusCode, kind: ResponseKind) -> Self {
        Self {
            status,
            kind,
            content_length: None,
            content_type: None,
            accept_ranges: false,
            last_modified: None,
            etag: None,
            age: None,
            content_range: None,
            retry_after: None,
        }
    }

    /// A proxy-generated error response with a `text/plain` body.
    #[must_use]
    pub(crate) fn error(status: StatusCode) -> Self {
        Self {
            content_type: Some(TEXT_PLAIN_UTF8),
            ..Self::bare(status, ResponseKind::Error)
        }
    }

    /// The `200 Connection Established` head answering a `CONNECT`.
    #[must_use]
    pub(crate) const fn tunnel_established() -> Self {
        Self::bare(StatusCode::OK, ResponseKind::TunnelEstablished)
    }

    /// The `304 Not Modified` head answering a satisfied conditional request.
    ///
    /// Carries the cached representation's validators and nothing else. No
    /// `Content-Length`: RFC 9110 section 8.6 permits one on a 304 only when
    /// it equals the 200 representation's length, which `0` never does. No
    /// `Accept-Ranges` either — it is advertised on the
    /// representation-bearing responses only. Both backends answer a 304
    /// with this head, so the shape cannot drift between them.
    #[must_use]
    pub(crate) fn not_modified(last_modified: &'a str, etag: Option<&'a str>, age: u32) -> Self {
        Self {
            last_modified: Some(last_modified),
            etag,
            age: Some(age),
            ..Self::bare(StatusCode::NOT_MODIFIED, ResponseKind::Success)
        }
    }

    /// The `416 Range Not Satisfiable` head for a request no byte of the
    /// representation satisfies.
    ///
    /// An `Error` head, so it carries `Server:` like every other
    /// proxy-generated rejection. The wire renderer adds
    /// `content_length: Some(0)` to frame the empty body for keep-alive;
    /// hyper emits that itself for an empty body.
    #[must_use]
    pub(crate) fn range_not_satisfiable(file_size: u64) -> Self {
        Self {
            content_range: Some(Self::unsatisfied_range(file_size)),
            ..Self::bare(StatusCode::RANGE_NOT_SATISFIABLE, ResponseKind::Error)
        }
    }

    /// The `Content-Range: bytes */<size>` value of a `416`.
    #[must_use]
    fn unsatisfied_range(file_size: u64) -> Cow<'a, str> {
        Cow::Owned(format!("bytes */{file_size}"))
    }

    /// Whether the renderers emit `Server:`.
    #[must_use]
    const fn emits_server(&self) -> bool {
        match self.kind {
            ResponseKind::Error | ResponseKind::TunnelEstablished => true,
            ResponseKind::Success => false,
        }
    }

    /// Whether the renderers emit `Connection:`.
    #[must_use]
    const fn emits_connection(&self) -> bool {
        match self.kind {
            ResponseKind::Error | ResponseKind::Success => true,
            ResponseKind::TunnelEstablished => false,
        }
    }

    /// Whether the renderers emit `Allow: GET`.
    #[must_use]
    fn emits_allow(&self) -> bool {
        self.status == StatusCode::METHOD_NOT_ALLOWED
    }
}

/// `Retry-After` seconds for a throttle window with `remaining` left: the
/// window rounded up to whole seconds, so a client retrying exactly on time
/// never lands inside it.
#[must_use]
pub(crate) fn retry_after_secs(remaining: std::time::Duration) -> u32 {
    u32::try_from(remaining.as_secs().saturating_add(1)).unwrap_or(u32::MAX)
}

#[cfg(feature = "hyper")]
impl ResponseHead<'_> {
    /// Render the head onto a hyper [`http::Response`] carrying `body`.
    ///
    /// `Connection:` is always `keep-alive` here; hyper decides the actual
    /// connection fate from the request.
    #[must_use]
    pub(crate) fn into_hyper<B>(self, body: B) -> http::Response<B> {
        use http::{
            HeaderValue,
            header::{
                ACCEPT_RANGES, AGE, ALLOW, CONNECTION, CONTENT_LENGTH, CONTENT_RANGE, CONTENT_TYPE,
                DATE, ETAG, LAST_MODIFIED, RETRY_AFTER, SERVER, VIA,
            },
        };

        use crate::{
            build_info::{APP_NAME, APP_VIA},
            http_range::format_http_date,
        };

        let emits_server = self.emits_server();
        let emits_connection = self.emits_connection();
        let emits_allow = self.emits_allow();
        let Self {
            status,
            kind: _,
            content_length,
            content_type,
            accept_ranges,
            last_modified,
            etag,
            age,
            content_range,
            retry_after,
        } = self;

        let mut builder = http::Response::builder().status(status);
        if emits_server {
            builder = builder.header(SERVER, APP_NAME);
        }
        builder = builder
            .header(VIA, APP_VIA)
            .header(DATE, &*format_http_date());
        if emits_connection {
            builder = builder.header(CONNECTION, "keep-alive");
        }
        if let Some(content_type) = content_type {
            builder = builder.header(CONTENT_TYPE, content_type);
        }
        if let Some(content_length) = content_length {
            builder = builder.header(CONTENT_LENGTH, HeaderValue::from(content_length));
        }
        if let Some(content_range) = content_range {
            builder = builder.header(
                CONTENT_RANGE,
                HeaderValue::try_from(&*content_range).expect("content range is valid"),
            );
        }
        if let Some(last_modified) = last_modified {
            builder = builder.header(
                LAST_MODIFIED,
                HeaderValue::try_from(last_modified).expect("HTTP date is valid"),
            );
        }
        if let Some(etag) = etag {
            builder = builder.header(
                ETAG,
                HeaderValue::try_from(etag).expect("ETag is validated before passing"),
            );
        }
        if accept_ranges {
            builder = builder.header(ACCEPT_RANGES, "bytes");
        }
        if let Some(age) = age {
            builder = builder.header(AGE, HeaderValue::from(age));
        }
        if let Some(retry_after) = retry_after {
            builder = builder.header(RETRY_AFTER, HeaderValue::from(retry_after));
        }
        if emits_allow {
            builder = builder.header(ALLOW, "GET");
        }

        builder.body(body).expect("HTTP response is valid")
    }
}

/// How the body follows a head written by [`ResponseHead::write_to`].
#[cfg(feature = "sendfile")]
#[derive(Copy, Clone)]
pub(crate) enum WireBody<'a> {
    /// No body bytes follow (`304`, `416`, tunnel establishment).
    None,
    /// A small body written together with the head in one buffer.
    Inline(&'a str),
    /// Body bytes follow via `sendfile(2)`/`splice(2)`: the head goes out
    /// with `MSG_MORE` so the kernel coalesces it with the first body
    /// segment.  A zero `Content-Length` writes plainly instead, as no body
    /// bytes will arrive to flush a held segment.
    Follows,
}

#[cfg(feature = "sendfile")]
impl ResponseHead<'_> {
    /// Render the status line and header block as wire bytes, terminated by
    /// the empty line.
    #[must_use]
    fn render(&self, conn_version: ConnectionVersion, conn_action: ConnectionAction) -> String {
        use crate::{
            build_info::{APP_NAME, APP_VIA},
            http_helpers::OptHeader,
            http_range::format_http_date,
            swrite,
        };

        let Self {
            status,
            kind,
            content_length,
            content_type,
            accept_ranges,
            last_modified,
            etag,
            age,
            content_range,
            retry_after,
        } = self;

        let mut out = String::with_capacity(256);
        match kind {
            ResponseKind::TunnelEstablished => {
                swrite!(out, "{conn_version} 200 Connection Established\r\n");
            }
            ResponseKind::Success | ResponseKind::Error => {
                swrite!(out, "{conn_version} {status}\r\n");
            }
        }
        if self.emits_server() {
            swrite!(out, "Server: {APP_NAME}\r\n");
        }
        swrite!(out, "Via: {APP_VIA}\r\nDate: {}\r\n", format_http_date());
        if self.emits_connection() {
            swrite!(out, "Connection: {conn_action}\r\n");
        }
        swrite!(
            out,
            "{}{}{}{}{}{}{}{}{}\r\n",
            OptHeader("Content-Type", *content_type),
            OptHeader("Content-Length", *content_length),
            OptHeader("Content-Range", content_range.as_deref()),
            OptHeader("Last-Modified", *last_modified),
            OptHeader("ETag", *etag),
            OptHeader("Accept-Ranges", (*accept_ranges).then_some("bytes")),
            OptHeader("Age", *age),
            OptHeader("Retry-After", *retry_after),
            OptHeader("Allow", self.emits_allow().then_some("GET")),
        );
        out
    }

    /// Write the head (and an inline body, if any) to the raw client stream.
    ///
    /// Records the client status metric; times out after the configured
    /// HTTP timeout.
    pub(crate) async fn write_to(
        &self,
        stream: &tokio::net::TcpStream,
        conn_version: ConnectionVersion,
        conn_action: ConnectionAction,
        body: WireBody<'_>,
    ) -> std::io::Result<()> {
        use tracing::trace;

        use crate::{
            http_helpers::{WritePhase, write_all_to_stream, write_all_to_stream_msg_more},
            metrics,
        };

        let mut response = self.render(conn_version, conn_action);
        trace!("Outgoing response head:\n{response}");
        if let WireBody::Inline(body) = body {
            response.push_str(body);
        }
        metrics::record_client_status(self.status);
        match body {
            WireBody::Follows if self.content_length.is_some_and(|len| len > 0) => {
                write_all_to_stream_msg_more(stream, response.as_bytes()).await
            }
            WireBody::None | WireBody::Inline(_) | WireBody::Follows => {
                write_all_to_stream(stream, response.as_bytes(), WritePhase::Header).await
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parallel_hack::NUDGE_BODY;

    /// A config with the parallel-download hack on its defaults (`429`,
    /// `Retry-After: 5`), for the two nudge-head renderer tests. Built by
    /// deserializing an empty document because `Config`'s `present` field is
    /// private to `config.rs`.
    #[cfg(any(feature = "hyper", feature = "sendfile"))]
    fn nudge_config() -> crate::config::Config {
        let mut config: crate::config::Config =
            toml::from_str("").expect("built-in defaults must parse");
        config.experimental_parallel_hack_enabled = true;
        config
    }

    #[cfg(feature = "hyper")]
    mod hyper {
        use http::header::{
            ACCEPT_RANGES, AGE, ALLOW, CONNECTION, CONTENT_LENGTH, CONTENT_RANGE, CONTENT_TYPE,
            DATE, ETAG, LAST_MODIFIED, RETRY_AFTER, SERVER, VIA,
        };

        use super::*;
        use crate::build_info::{APP_NAME, APP_VIA};

        fn render(head: ResponseHead<'_>) -> http::Response<()> {
            head.into_hyper(())
        }

        #[test]
        fn success_head_has_via_date_connection_but_no_server() {
            let response = render(ResponseHead {
                content_length: Some(12),
                content_type: Some("application/octet-stream"),
                accept_ranges: true,
                last_modified: Some("Wed, 20 Dec 2023 04:45:32 GMT"),
                etag: Some("\"abc\""),
                age: Some(7),
                ..ResponseHead::bare(StatusCode::OK, ResponseKind::Success)
            });
            let headers = response.headers();
            assert_eq!(response.status(), StatusCode::OK);
            assert_eq!(headers.get(VIA).unwrap(), APP_VIA);
            assert!(headers.contains_key(DATE));
            assert_eq!(headers.get(CONNECTION).unwrap(), "keep-alive");
            assert!(!headers.contains_key(SERVER));
            assert_eq!(headers.get(CONTENT_LENGTH).unwrap(), "12");
            assert_eq!(
                headers.get(CONTENT_TYPE).unwrap(),
                "application/octet-stream"
            );
            assert_eq!(headers.get(ACCEPT_RANGES).unwrap(), "bytes");
            assert_eq!(
                headers.get(LAST_MODIFIED).unwrap(),
                "Wed, 20 Dec 2023 04:45:32 GMT"
            );
            assert_eq!(headers.get(ETAG).unwrap(), "\"abc\"");
            assert_eq!(headers.get(AGE).unwrap(), "7");
            assert!(!headers.contains_key(CONTENT_RANGE));
            assert!(!headers.contains_key(RETRY_AFTER));
            assert!(!headers.contains_key(ALLOW));
        }

        #[test]
        fn error_head_has_server_and_text_plain() {
            let response = render(ResponseHead::error(StatusCode::BAD_GATEWAY));
            let headers = response.headers();
            assert_eq!(response.status(), StatusCode::BAD_GATEWAY);
            assert_eq!(headers.get(SERVER).unwrap(), APP_NAME);
            assert_eq!(headers.get(VIA).unwrap(), APP_VIA);
            assert!(headers.contains_key(DATE));
            assert_eq!(headers.get(CONNECTION).unwrap(), "keep-alive");
            assert_eq!(headers.get(CONTENT_TYPE).unwrap(), TEXT_PLAIN_UTF8);
            // Left to hyper's body size hint.
            assert!(!headers.contains_key(CONTENT_LENGTH));
            assert!(!headers.contains_key(ALLOW));
            assert!(!headers.contains_key(RETRY_AFTER));
        }

        #[test]
        fn method_not_allowed_carries_allow() {
            let response = render(ResponseHead::error(StatusCode::METHOD_NOT_ALLOWED));
            assert_eq!(response.headers().get(ALLOW).unwrap(), "GET");
        }

        #[test]
        fn retry_after_is_emitted_when_set() {
            let response = render(ResponseHead {
                retry_after: Some(42),
                ..ResponseHead::error(StatusCode::SERVICE_UNAVAILABLE)
            });
            assert_eq!(response.headers().get(RETRY_AFTER).unwrap(), "42");
        }

        /// The `416` head `hyper_conn.rs`'s `ServePlan::NotSatisfiable` arm
        /// builds: an `Error` head naming the current representation length,
        /// with `Content-Length` left to the empty body.
        #[test]
        fn unsatisfied_range_carries_content_range() {
            let response = render(ResponseHead {
                content_range: Some(ResponseHead::unsatisfied_range(1234)),
                ..ResponseHead::bare(StatusCode::RANGE_NOT_SATISFIABLE, ResponseKind::Error)
            });
            let headers = response.headers();
            assert_eq!(response.status(), StatusCode::RANGE_NOT_SATISFIABLE);
            assert_eq!(headers.get(CONTENT_RANGE).unwrap(), "bytes */1234");
            assert!(headers.contains_key(SERVER));
            assert!(!headers.contains_key(CONTENT_TYPE));
            assert!(!headers.contains_key(CONTENT_LENGTH));
        }

        /// The `304` head `hyper_conn.rs`'s `ServePlan::NotModified` arm
        /// builds: validators and `Age` only.  No `Content-Length` (RFC 9110
        /// §8.6 permits one only when it equals the `200` representation's
        /// length), no `Accept-Ranges`, and no `Server:` — a 304 answers on
        /// the origin's behalf.  `http_helpers::write_304_response` must
        /// stay header-for-header identical; see the `wire` twin of this
        /// test.
        #[test]
        fn not_modified_head_carries_validators_only() {
            let response = render(ResponseHead {
                last_modified: Some("Wed, 20 Dec 2023 04:45:32 GMT"),
                etag: Some("\"abc\""),
                age: Some(7),
                ..ResponseHead::bare(StatusCode::NOT_MODIFIED, ResponseKind::Success)
            });
            let headers = response.headers();
            assert_eq!(response.status(), StatusCode::NOT_MODIFIED);
            assert_eq!(
                headers.get(LAST_MODIFIED).unwrap(),
                "Wed, 20 Dec 2023 04:45:32 GMT"
            );
            assert_eq!(headers.get(ETAG).unwrap(), "\"abc\"");
            assert_eq!(headers.get(AGE).unwrap(), "7");
            assert_eq!(headers.get(CONNECTION).unwrap(), "keep-alive");
            assert!(headers.contains_key(DATE));
            assert_eq!(headers.get(VIA).unwrap(), APP_VIA);
            assert!(!headers.contains_key(CONTENT_LENGTH));
            assert!(!headers.contains_key(ACCEPT_RANGES));
            assert!(!headers.contains_key(CONTENT_TYPE));
            assert!(!headers.contains_key(SERVER));
        }

        #[test]
        fn tunnel_established_has_server_but_no_connection() {
            let response = render(ResponseHead::tunnel_established());
            let headers = response.headers();
            assert_eq!(response.status(), StatusCode::OK);
            assert_eq!(headers.get(SERVER).unwrap(), APP_NAME);
            assert_eq!(headers.get(VIA).unwrap(), APP_VIA);
            assert!(headers.contains_key(DATE));
            assert!(!headers.contains_key(CONNECTION));
        }

        /// The parallel-hack nudge, which both backends render from the one
        /// head in `parallel_hack::nudge_head`: a keep-alive `Success` head,
        /// so no `Server:`, and exactly one `Content-Length` -- the head sets
        /// it explicitly, so hyper must not derive a second one from the
        /// body's size hint.
        #[test]
        fn parallel_hack_nudge_head_is_pinned() {
            let response = crate::parallel_hack::nudge_head(&nudge_config())
                .into_hyper(crate::proxy_body::full_body(NUDGE_BODY));
            let headers = response.headers();
            assert_eq!(response.status(), StatusCode::TOO_MANY_REQUESTS);
            assert_eq!(headers.get(RETRY_AFTER).unwrap(), "5");
            assert_eq!(headers.get(CONTENT_LENGTH).unwrap(), "20");
            assert_eq!(headers.get_all(CONTENT_LENGTH).iter().count(), 1);
            assert_eq!(headers.get(CONNECTION).unwrap(), "keep-alive");
            assert_eq!(headers.get(VIA).unwrap(), APP_VIA);
            assert!(headers.contains_key(DATE));
            assert!(!headers.contains_key(SERVER), "a nudge is not an error");
            assert!(!headers.contains_key(CONTENT_TYPE));
        }
    }

    #[cfg(feature = "sendfile")]
    mod wire {
        use super::*;
        use crate::build_info::{APP_NAME, APP_VIA};

        fn render(head: &ResponseHead<'_>) -> String {
            head.render(ConnectionVersion::Http11, ConnectionAction::KeepAlive)
        }

        /// Header lines of a rendered head, without the status line.
        fn header_lines(wire: &str) -> Vec<&str> {
            let (block, rest) = wire.split_once("\r\n\r\n").expect("head is terminated");
            assert!(rest.is_empty(), "nothing follows the head: {rest:?}");
            block.split("\r\n").skip(1).collect()
        }

        fn has_header(lines: &[&str], name: &str) -> bool {
            lines.iter().any(|line| {
                line.split_once(": ")
                    .is_some_and(|(n, _)| n.eq_ignore_ascii_case(name))
            })
        }

        #[test]
        fn success_head_has_via_date_connection_but_no_server() {
            let wire = render(&ResponseHead {
                content_length: Some(12),
                content_type: Some("application/octet-stream"),
                accept_ranges: true,
                last_modified: Some("Wed, 20 Dec 2023 04:45:32 GMT"),
                etag: Some("\"abc\""),
                age: Some(7),
                ..ResponseHead::bare(StatusCode::OK, ResponseKind::Success)
            });
            assert!(wire.starts_with("HTTP/1.1 200 OK\r\n"), "{wire}");
            let lines = header_lines(&wire);
            assert!(
                lines.contains(&format!("Via: {APP_VIA}").as_str()),
                "{wire}"
            );
            assert!(has_header(&lines, "Date"), "{wire}");
            assert!(lines.contains(&"Connection: keep-alive"), "{wire}");
            assert!(!has_header(&lines, "Server"), "{wire}");
            assert!(lines.contains(&"Content-Length: 12"), "{wire}");
            assert!(
                lines.contains(&"Content-Type: application/octet-stream"),
                "{wire}"
            );
            assert!(lines.contains(&"Accept-Ranges: bytes"), "{wire}");
            assert!(
                lines.contains(&"Last-Modified: Wed, 20 Dec 2023 04:45:32 GMT"),
                "{wire}"
            );
            assert!(lines.contains(&"ETag: \"abc\""), "{wire}");
            assert!(lines.contains(&"Age: 7"), "{wire}");
            assert!(!has_header(&lines, "Content-Range"), "{wire}");
            assert!(!has_header(&lines, "Retry-After"), "{wire}");
            assert!(!has_header(&lines, "Allow"), "{wire}");
        }

        #[test]
        fn error_head_has_server_and_honours_connection_action() {
            let head = ResponseHead {
                content_length: Some(5),
                ..ResponseHead::error(StatusCode::BAD_GATEWAY)
            };
            let wire = head.render(ConnectionVersion::Http10, ConnectionAction::Close);
            assert!(wire.starts_with("HTTP/1.0 502 Bad Gateway\r\n"), "{wire}");
            let lines = header_lines(&wire);
            assert!(
                lines.contains(&format!("Server: {APP_NAME}").as_str()),
                "{wire}"
            );
            assert!(
                lines.contains(&format!("Via: {APP_VIA}").as_str()),
                "{wire}"
            );
            assert!(has_header(&lines, "Date"), "{wire}");
            assert!(lines.contains(&"Connection: close"), "{wire}");
            assert!(
                lines.contains(&"Content-Type: text/plain; charset=utf-8"),
                "{wire}"
            );
            assert!(lines.contains(&"Content-Length: 5"), "{wire}");
            assert!(!has_header(&lines, "Allow"), "{wire}");
            assert!(!has_header(&lines, "Retry-After"), "{wire}");
        }

        #[test]
        fn method_not_allowed_carries_allow() {
            let wire = render(&ResponseHead::error(StatusCode::METHOD_NOT_ALLOWED));
            assert!(header_lines(&wire).contains(&"Allow: GET"), "{wire}");
        }

        #[test]
        fn retry_after_is_emitted_when_set() {
            let wire = render(&ResponseHead {
                retry_after: Some(42),
                ..ResponseHead::error(StatusCode::SERVICE_UNAVAILABLE)
            });
            assert!(header_lines(&wire).contains(&"Retry-After: 42"), "{wire}");
        }

        /// `http_helpers::write_416_response` builds exactly this head: the
        /// hyper `416` plus the explicit `Content-Length: 0` that frames the
        /// empty body on a keep-alive raw socket.
        #[test]
        fn unsatisfied_range_carries_content_range() {
            let wire = render(&ResponseHead {
                content_length: Some(0),
                content_range: Some(ResponseHead::unsatisfied_range(1234)),
                ..ResponseHead::bare(StatusCode::RANGE_NOT_SATISFIABLE, ResponseKind::Error)
            });
            assert!(
                wire.starts_with("HTTP/1.1 416 Range Not Satisfiable\r\n"),
                "{wire}"
            );
            let lines = header_lines(&wire);
            assert!(lines.contains(&"Content-Range: bytes */1234"), "{wire}");
            assert!(lines.contains(&"Content-Length: 0"), "{wire}");
            assert!(
                lines.contains(&format!("Server: {APP_NAME}").as_str()),
                "{wire}"
            );
            assert!(!has_header(&lines, "Content-Type"), "{wire}");
        }

        /// `http_helpers::write_304_response` builds exactly this head; it
        /// must stay header-for-header the hyper backend's 304.
        #[test]
        fn not_modified_head_carries_validators_only() {
            let wire = render(&ResponseHead {
                last_modified: Some("Wed, 20 Dec 2023 04:45:32 GMT"),
                etag: Some("\"abc\""),
                age: Some(7),
                ..ResponseHead::bare(StatusCode::NOT_MODIFIED, ResponseKind::Success)
            });
            assert!(wire.starts_with("HTTP/1.1 304 Not Modified\r\n"), "{wire}");
            let lines = header_lines(&wire);
            assert!(
                lines.contains(&"Last-Modified: Wed, 20 Dec 2023 04:45:32 GMT"),
                "{wire}"
            );
            assert!(lines.contains(&"ETag: \"abc\""), "{wire}");
            assert!(lines.contains(&"Age: 7"), "{wire}");
            assert!(lines.contains(&"Connection: keep-alive"), "{wire}");
            assert!(has_header(&lines, "Date"), "{wire}");
            assert!(
                lines.contains(&format!("Via: {APP_VIA}").as_str()),
                "{wire}"
            );
            assert!(!has_header(&lines, "Content-Length"), "{wire}");
            assert!(!has_header(&lines, "Accept-Ranges"), "{wire}");
            assert!(!has_header(&lines, "Content-Type"), "{wire}");
            assert!(!has_header(&lines, "Server"), "{wire}");
        }

        /// The wire bytes of the parallel-hack nudge head, pinned in full:
        /// the sendfile/splice backends write these plus the inline body.
        #[test]
        fn parallel_hack_nudge_head_is_pinned() {
            let wire = render(&crate::parallel_hack::nudge_head(&nudge_config()));
            assert!(
                wire.starts_with("HTTP/1.1 429 Too Many Requests\r\n"),
                "{wire}"
            );
            let lines = header_lines(&wire);
            assert!(!has_header(&lines, "Server"), "a nudge is not an error");
            assert!(
                lines.contains(&format!("Via: {APP_VIA}").as_str()),
                "{wire}"
            );
            assert!(has_header(&lines, "Date"), "{wire}");
            assert!(lines.contains(&"Connection: keep-alive"), "{wire}");
            assert!(lines.contains(&"Content-Length: 20"), "{wire}");
            assert!(lines.contains(&"Retry-After: 5"), "{wire}");
            assert!(!has_header(&lines, "Content-Type"), "{wire}");
            assert_eq!(NUDGE_BODY.len(), 20, "the pinned body length");
        }

        #[test]
        fn tunnel_established_has_server_but_no_connection() {
            let wire = render(&ResponseHead::tunnel_established());
            assert!(
                wire.starts_with("HTTP/1.1 200 Connection Established\r\n"),
                "{wire}"
            );
            let lines = header_lines(&wire);
            assert!(
                lines.contains(&format!("Server: {APP_NAME}").as_str()),
                "{wire}"
            );
            assert!(
                lines.contains(&format!("Via: {APP_VIA}").as_str()),
                "{wire}"
            );
            assert!(has_header(&lines, "Date"), "{wire}");
            assert!(!has_header(&lines, "Connection"), "{wire}");
            assert!(!has_header(&lines, "Content-Length"), "{wire}");
        }
    }

    #[test]
    fn retry_after_rounds_up_to_whole_seconds() {
        use std::time::Duration;

        assert_eq!(retry_after_secs(Duration::ZERO), 1);
        assert_eq!(retry_after_secs(Duration::from_millis(1500)), 2);
        assert_eq!(retry_after_secs(Duration::from_secs(u64::MAX)), u32::MAX);
    }
}
