name: Periodic Security audit
on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security_audit:
    permissions:
      issues: write
      issues-reason: to create issues
      checks: write
      checks-reason: to create check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
