name: Audit Dependencies

on:
  push:
    paths:
      - ".github/workflows/audit.yml"
      - "**/audit.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  pull_request:
    paths:
      - ".github/workflows/audit.yml"
      - "**/audit.toml"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  audit:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
