name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: read

    name: Rust Build
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
      SQLX_OFFLINE: true

    steps:
      - uses: actions/checkout@v6

      - name: Build (default features)
        run: cargo build --verbose

      - name: Build (default+splice feature)
        run: cargo build --verbose --features splice

      - name: Build (default+splice+ktls features)
        run: cargo build --verbose --features splice,ktls

      - name: Build (sendfile -mmap)
        run: cargo build --verbose --no-default-features --features tls_rustls,sendfile

      - name: Build (tls_hyper feature)
        run: cargo build --verbose --no-default-features --features tls_hyper

      - name: Build (splice + tls_hyper, no ktls)
        run: cargo build --verbose --no-default-features --features tls_hyper,splice

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy (default features)
        run: cargo clippy --all-targets -- -D warnings -D clippy::pedantic

      - name: Clippy (default+splice feature)
        run: cargo clippy --all-targets --features splice -- -D warnings -D clippy::pedantic

      - name: Clippy (default+splice+ktls features)
        run: cargo clippy --all-targets --features splice,ktls -- -D warnings -D clippy::pedantic

      - name: Clippy (sendfile -mmap)
        run: cargo clippy --all-targets --no-default-features --features tls_rustls,sendfile -- -D warnings -D clippy::pedantic

      - name: Clippy (tls_hyper feature)
        run: cargo clippy --all-targets --no-default-features --features tls_hyper -- -D warnings -D clippy::pedantic

      - name: Clippy (splice + tls_hyper, no ktls)
        run: cargo clippy --all-targets --no-default-features --features tls_hyper,splice -- -D warnings -D clippy::pedantic

      - name: Run tests (default features)
        run: cargo test --verbose

      - name: Run tests (default+splice features)
        run: cargo test --verbose --features splice

      - name: Run tests (default+splice+ktls features)
        run: cargo test --verbose --features splice,ktls

      - name: Run tests (tls_hyper feature)
        run: cargo test --verbose --no-default-features --features tls_hyper

      - name: Run tests (splice + tls_hyper, no ktls)
        run: cargo test --verbose --no-default-features --features tls_hyper,splice

  spaces-check:
    permissions:
      contents: read

    name: Spaces Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Spaces check
        run: git diff-tree --check $(git hash-object -t tree /dev/null) HEAD

  spellings:
    permissions:
      contents: read

    name: Codespell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install codespell
        run: sudo apt-get install -y codespell

      - name: Run codespell
        run: codespell -L crate,te debian/ src/ apt-cacher-rs.conf apt-cacher-rs.init apt-cacher-rs.service README.md TODO
