name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: read

    name: Rust Build
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
      SQLX_OFFLINE: true

    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@cargo-hack
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Build
        run: cargo hack --feature-powerset --at-least-one-of tls_hyper,tls_rustls --mutually-exclusive-features tls_hyper,tls_rustls --verbose build --verbose

      - name: Lint via Clippy
        run: cargo hack --feature-powerset --at-least-one-of tls_hyper,tls_rustls --mutually-exclusive-features tls_hyper,tls_rustls --verbose clippy --all-targets -- -D warnings -D clippy::pedantic

      - name: Test
        run: cargo hack --feature-powerset --at-least-one-of tls_hyper,tls_rustls --mutually-exclusive-features tls_hyper,tls_rustls --verbose test --verbose

  formatting:
    permissions:
      contents: read

    name: Rust source formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
